### ISSUE TITLE
Create splash screen

### ISSUE THREAD

**Issue by uioporqwerty** [uioporqwerty/Repeat-App#7]
Splash screen should be available for iOS and Android.

![Splash Screen.png](https://images.zenhubusercontent.com/59fbe90f8a75884b9085e17a/69ef0130-2286-4111-8ec4-6b1ad8a8dd72)

**Comment by dlee11** [comment]
![app-bg](https://user-images.githubusercontent.com/10914647/34245679-e68b3a04-e5df-11e7-92a0-54897612bb72.png)
![app-icon](https://user-images.githubusercontent.com/10914647/34245680-e6a402f0-e5df-11e7-80c7-0c4fcf90db28.png)
